consider_water_app/config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :users, only: [:new, :create, :show, :destroy] do
    resources :journal_entries
    resources :mood_ratings
  end

  resources :breaths, only:[:index]
  resources :esques, only:[:index]
  resources :colors, only:[:index]
  resources :abouts, only:[:index]

get 'sessions/new' => 'sessions#new'
post 'sessions' => 'sessions#create'
delete 'sessions' => 'sessions#destroy'

end

consider_water_app/app/models/journal_entry.rb
class JournalEntry < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
end

consider_water_app/app/models/mood_rating.rb
class MoodRating < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
end

consider_water_app/app/models/user.rb
class User < ActiveRecord::Base

  has_many :journal_entries, dependent: :destroy
  has_many :mood_ratings, dependent: :destroy
  validates :username, presence: true, uniqueness:true
  has_secure_password
end

consider_water_app/app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
end

consider_water_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    if session[:current_user_id]
      @user ||= User.find(session[:current_user_id])
    end
  end
end

consider_water_app/app/controllers/breaths_controller.rb
class BreathsController < ApplicationController
  def index
    current_user
  end
end

consider_water_app/app/controllers/colors_controller.rb
class ColorsController < ApplicationController
end

consider_water_app/app/controllers/esques_controller.rb
class EsquesController < ApplicationController
end

consider_water_app/app/controllers/graph_controller.rb
class GraphController < ApplicationController
  def index
    current_user
    @mood_ratings = User.find(session[:current_user_id]).mood_ratings
    # this renders json instead of the expected view...hrmmm
    # on the path to d3 graphing
    #render json: @mood_ratings
  end


  def data
    current_user
    @array = [1,2,3,4,5,6,7,8,9,10]

    @mood_charting = User.find(session[:current_user_id]).mood_ratings
    respond_to do |format|
      format.json {
        render :json => @mood_charting

        # renders [object Object]
        #render :json => @mood_ratings

      }
    end
  end
end

consider_water_app/app/controllers/journal_entries_controller.rb
class JournalEntriesController < ApplicationController

  def index
    current_user
    @journal_entries = User.find(session[:current_user_id]).journal_entries.order(created_at: :desc)
  end

  def show
    current_user
    @journal_entry = JournalEntry.find(params[:id])
  end

  def new
    current_user
    @journal_entry = current_user.journal_entries.new
  end

# use .build rather than .new when new things have an association?
  def create
    @journal_entry = current_user.journal_entries.build(journal_entry_params)
    if @journal_entry.save
      redirect_to user_journal_entries_path(@journal_entry)
    else
      #some sort of error message?
    end
  end


  def edit
    @journal_entry = current_user.journal_entries.find(params[:id])
    # @journal_entry = JournalEntry.find(params[:id])
  end

  def update
    @journal_entry = JournalEntry.find(params[:id])
    @journal_entry.update(journal_entry_params)
    redirect_to user_journal_entries_path
  end

  def destroy
    @journal_entry = JournalEntry.find(params[:id])
    @journal_entry.destroy
    redirect_to user_journal_entries_path
  end

private
  def journal_entry_params
    params.require(:journal_entry).permit(:entry_title, :entry_main, :user_id, :id)
  end

end

consider_water_app/app/controllers/mood_ratings_controller.rb
class MoodRatingsController < ApplicationController

  def index
    current_user
    @mood_ratings = User.find(session[:current_user_id]).mood_ratings.order(created_at: :desc)
  end

  def show
    current_user
    @mood_rating = MoodRating.find(params[:id])
  end

  def new
    current_user
    @mood_rating = current_user.mood_ratings.new
  end

  def create
    @mood_rating =
    current_user.mood_ratings.build(mood_rating_params)

    if @mood_rating.save
      redirect_to user_mood_ratings_path(@mood_rating)
    else
      # some sort of error message?
    end
  end
#don't know if I want to keep this function
#would need to update it to be more like journal_entries
  def edit
    @mood_rating = MoodRating.find(params[:id])
  end

  def update
    @mood_rating = MoodRating.find(params[:id])
    @mood_rating.update(mood_rating_params)
    redirect_to user_mood_ratings_path
  end

#don't know if I want to keep this function
  def destroy
    @mood_rating = MoodRating.find(params[:id])
    @mood.destroy
    #redirect_to ?
  end

private
  def mood_rating_params
 params.require(:mood_rating).permit(:rating, :user, :user_id, :id)
  end

end

consider_water_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:current_user_id] = user.id
      redirect_to root_path
    else
      #flash.now[:notice] = 'Invalid/username/password combination'
      render html: 'Invalid/username/password combination'
    #  redirect_to root_path
    end
  end

  def destroy
    session[:current_user_id] = nil
    redirect_to root_path
  end
end

consider_water_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

 #before_action :authenticate, except: [:new, :create]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:current_user_id] = @user.id
      redirect_to root_path
    else
      render html: 'Invalid/username/password. Please re-enter your information.'
      #redirect_to new_user_path
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    session[:current_user_id] = nil
    @user.destroy
    redirect_to root_path
  end

  def add_id
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end

end

consider_water_app/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    current_user
  end
end

consider_water_app/app/helpers/application_helper.rb
module ApplicationHelper
end

consider_water_app/app/views/abouts/index.html.erb
<div id="about">
  <h3>About</h3>
<p> This project is based on my own experiences in trying to cope with anxiety </p>

<p> <strong> Intro: </strong>In 2005 David Foster Wallace gave a speech to the graudating students of Kenyon College. It was titled "This is water." I read this speech every few months, it helps realign my internal compass. It turned out that DFW had an extensive library of self-help books that were heavily annoted. This inspired me to pursue self-help in all sorts of shapes and forms.   </p>

<p> <strong> Journal: </strong>Journaling has long been thought to be a theraputic tool. It seemed fitting to have a component like this. If not even as a proper daily journal- sometimes just writing something troubling thoughts down can help dissapate some of the feelings of distress.  </p>

<p> <strong> Mood: </strong>One of my closest friends has spent a long time talking to about how cool it would be track his moods and then graph them out. But he never was able to keep up tracking his mood for more than a few days. I don't know that this would even help. But this componenet is dedicated to him. </p>

<p> <strong> Breath: </strong> Becuase only second to 'just stop stressing'- this is the thing people always tell me to do('take deep breaths!'). Surely there must be something to it if everyone keeps telling me to do it.

<p> <strong> Feeling: </strong> I tried <a href = "http://www.emdr.com/"> EMDR </a>a few times. It definitely pushed me out of my comfort zone, I tink it may have even helped a little. I often wonder if circumstances had been different and I had continued, how it would have all turned out.

<p> <strong> Colors: </strong> This one, though the simplest to implement, has the most meaning for me and was the inspiration to build out the other pieces of this app. I once had the fortune of haivng one of the worst panic attacks of my life in the presense of a counselor who was able to walk me through from one end to the other, for the first time, without drug intervention. She used a bunch of different techniques on me, but kept coming back to colors. The ability to make it to the other end of a severe panic attack without medication was a profoundly freeing experience and I wouldn't be here today without having had her help. </p>
</div>

consider_water_app/app/views/breaths/index.html.erb
<div>
<div id="breath" class="breath-speed-3">
</div>
<div id="breath-speed-bar">
<div class="breath-speed-1-control"></div>
<div class="breath-speed-2-control"></div>
<div class="breath-speed-3-control"></div>
<div class="breath-speed-4-control"></div>
<div class="breath-speed-5-control"></div>
</div>
<p class="footer"> Take slow breaths  </p>

consider_water_app/app/views/colors/index.html.erb
<div class="colors">
<p>Your head is connected to your body.</p>
<p>Your feet are firmly touching the ground.</p>
<p>Look away from the screen, out and around.</p>
<p>Name the colors of the things you see.</p>
<p>You are present in the here and now. </p>
</div>

consider_water_app/app/views/esques/index.html.erb
<div id="burst-8" class="burst-8">
</div>
</div>
<div class="footer block">
<div class="feeling1"><p>These prompts will repeat. Click for the next prompt</p></div>
<div class="feeling2"><p>Take your time</p></div>
<div class="feeling3"><p>Stop whenever you want</p></div>
<div class="feeling4"><p>Be sure to breathe</p></div>
<div class="feeling5"><p>There are no correct answers</p></div>
<div class="feeling6"><p>Folow the pendulum with your eyes </p></div>
<div class="feeling7"><p>Focus on an uncomofortable feeling that you are currently experiencing</p></div>
<div class="feeling8"><p>Give the feeling a color</p></div>
<div class="feeling9"><p>Give the feeling a shape</p></div>
<div class="feeling10"><p>Give the feeling a texture</p></div>
<div class="feeling11"><p>Give the feeling a size</p></div>
<div class="feeling12"><p>Notice, does it have a temperature?</p></div>
<div class="feeling13"><p>Notice, does it have a sound?</p></div>
<div class="feeling14"><p>Notice, has this feeling changed?</p></div>
<div class="feeling15"><p>Are you able to move it?</p></div>
<div class="feeling16"><p>Notice how you are feeling</p></div>
<div class="feeling17"><p>Click again to repeat the prompts</p></div>

consider_water_app/app/views/graph/index.html.erb
<!-- <svg id="graph"></svg> -->

consider_water_app/app/views/journal_entries/_create_form.html.erb
<%= form_for [@user, @journal_entry] do |f| %>
  <%= f.label :entry_title %>
  <%= f.text_field :entry_title, size:80%>
  <%= f.label :entry_main %>
  <%= f.text_area :entry_main, cols:100, rows:20 %>
  <%= f.hidden_field :user_id, :value => :user_id %>
  <%= f.submit "save", :class => 'signup-button' %>
<% end %>

consider_water_app/app/views/journal_entries/_edit_form.html.erb
<%= form_for [@user, @journal_entry], url: user_journal_entry_path do |f| %>
  <%= f.label :entry_title %><br>
  <%= f.text_field :entry_title, size:80%><br>
  <%= f.label :entry_main %><br>
  <%= f.text_area :entry_main, cols:100, rows:15 %>
  <%= f.submit "save", :class => 'signup-button' %>
<% end %>

consider_water_app/app/views/journal_entries/_form.html.erb
<%= form_for @journal_entry do |f| %>
  <%= f.label :entry_title %>
  <%= f.text_field :entry_title, size:80, value: "default"%> 
  <%= f.label :entry_main %>
  <%= f.text_area :entry_main, cols:100, rows:40 %>
  <%= f.hidden_field :user_id, :value => :user_id %>
  <%= f.submit "save" %>
<% end %>

consider_water_app/app/views/journal_entries/_journal_entry.html.erb
<div class="entries-all">
  <h2> <%= journal_entry.entry_title %> </h2>
  <p> <%= journal_entry.created_at.to_s(:short) %> </p>
  <p> <%= journal_entry.entry_main %> </p>
  <%= link_to "Edit", edit_user_journal_entry_path(@user, journal_entry) %>
</div>

consider_water_app/app/views/journal_entries/edit.html.erb
<div class ="form">
  <%= render partial: 'edit_form' %> <br>
  <%= link_to "delete", user_journal_entry_path(@user, @journal_entry), method: :delete %>
</div>

consider_water_app/app/views/journal_entries/index.html.erb
<%= link_to "Create a new Journal Entry", new_user_journal_entry_path(@user) %>
<br>

<%= render @journal_entries %>

consider_water_app/app/views/journal_entries/new.html.erb
journal new!
<div class="form">
  <%= render partial: 'create_form' %>
</div>

consider_water_app/app/views/journal_entries/show.html.erb
journal show!
<div class="entries-all">
  <h2> <%= journal_entry.entry_title %> </h2>
  <p> <%= journal_entry.created_at.to_s(:short) %> </p>
  <p> <%= journal_entry.entry_main %> </p>
  <%= link_to "View", user_journal_entry_path(@user, journal_entry) %>
  <%= link_to "Edit", edit_user_journal_entry_path(@user, journal_entry) %>
</div>

consider_water_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Consider Water</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

<link href='https://fonts.googleapis.com/css?family=Abril+Fatface|Architects+Daughter|Josefin+Slab:400,100,400italic,100italic,600italic|Comfortaa:400,300,700|Philosopher:400,400italic|Old+Standard+TT:400,400italic|Tangerine|Arapey|Bad+Script' rel='stylesheet' type='text/css'>
</head>
<body>
  <h2 class="logo" > Consider Water  </h2>
  <div class="hello"><%= link_to  " ≈ ", root_path, :class => 'logo' %> </div>
  <div class="menu">
    <% if session[:current_user_id] %>
      <%= link_to "Journal", user_journal_entries_path(session[:current_user_id]) %>
      <%= link_to "Mood", user_mood_ratings_path(session[:current_user_id]) %>
    <% end %>
    <%= link_to "Colors", colors_path %>
    <%= link_to "Breath", breaths_path %>
    <%= link_to "Feeling", esques_path %>
    <%= link_to "About", abouts_path %>
  </div>
  <div class="login">
    <% if session[:current_user_id] %>
    <%= link_to "#{User.find(session[:current_user_id]).username}", user_path(session[:current_user_id]) %> ✧
    <%= link_to "Logout", sessions_path, method: :delete %>
    <% else %>
  <br>
    <%= form_tag(sessions_path) do%>
    <%= label_tag :username %>
    <%= text_field_tag :username %>
    <br>
    <%= label_tag :password %>
    <%= password_field_tag :password %>
    <br>
    <%= submit_tag "Login", :class => 'login-button'  %>
    <div class="signup">
      <%= link_to "Sign up", new_user_url, method: :get %>
    </div>
    <% end %>
    <% end %>
  </div>
<div id="container">

<%= yield %>
</div>
</body>
</html>

consider_water_app/app/views/mood_ratings/_form.html.erb
<div class="bar-mood">
  <div class="mood10">10<input class="mood" type="hidden" value="10">
    <%= form_for [@user, @mood_rating] do |f| %>
       <%= f.hidden_field :rating, :value => 10 %>
       <%= f.submit "10" ,:class => 'new_mood_rating' %>
    <% end %>
  </div>
  <div class="mood9">9<input class="mood" type="hidden" value="9">
    <%= form_for [@user, @mood_rating] do |f| %>
      <%= f.hidden_field :rating, :value => 9 %>
      <%= f.submit "9",:class => 'new_mood_rating' %>
    <% end %>
  </div>
  <div class="mood8">8<input class="mood" type="hidden" value="8">
    <%= form_for [@user, @mood_rating] do |f| %>
      <%= f.hidden_field :rating, :value => 8 %>
    <%= f.submit "8",:class => 'new_mood_rating' %>
    <% end %>
  </div>

  <div class="mood7">7<input class="mood" type="hidden" value="7">
    <%= form_for [@user, @mood_rating] do |f| %>
      <%= f.hidden_field :rating, :value => 7 %>
      <%= f.submit "7",:class => 'new_mood_rating' %>
    <% end %>
  </div>

  <div class="mood6">6<input class="mood" type="hidden" value="6">
    <%= form_for [@user, @mood_rating] do |f| %>
      <%= f.hidden_field :rating, :value => 6 %>
      <%= f.submit "6",:class => 'new_mood_rating' %>
    <% end %>
  </div>

  <div class="mood5">5<input class="mood" type="hidden" value="5">
    <%= form_for [@user, @mood_rating] do |f| %>
      <%= f.hidden_field :rating, :value => 5 %>
      <%= f.submit "5",:class => 'new_mood_rating' %>
    <% end %>
  </div>

  <div class="mood4">4<input class="mood" type="hidden" value="4">
    <%= form_for [@user, @mood_rating] do |f| %>
      <%= f.hidden_field :rating, :value => 4 %>
      <%= f.submit "4",:class => 'new_mood_rating' %>
    <% end %>
  </div>

  <div class="mood3">3<input class="mood" type="hidden" value="3">
    <%= form_for [@user, @mood_rating] do |f| %>
      <%= f.hidden_field :rating, :value => 3 %>
      <%= f.submit "3",:class => 'new_mood_rating' %>
    <% end %>
  </div>

  <div class="mood2">2<input class="mood" type="hidden" value="2">
    <%= form_for [@user, @mood_rating] do |f| %>
      <%= f.hidden_field :rating, :value => 2 %>
      <%= f.submit "2",:class => 'new_mood_rating' %>
    <% end %>
  </div>

  <div class="mood1">1<input class="mood" type="hidden" value="1">
    <%= form_for [@user, @mood_rating] do |f| %>
      <%= f.hidden_field :rating, :value => 1 %>
      <%= f.submit "1",:class => 'new_mood_rating' %>
    <% end %>
  </div>

</div>

consider_water_app/app/views/mood_ratings/_mood_rating.html.erb
<tr>
    <td><%= mood_rating.rating %></td>
    <td> <%= mood_rating.created_at.to_s(:short) %> </td>
</tr>

consider_water_app/app/views/mood_ratings/index.html.erb
<br>
<%= link_to "Enter your current mood", new_user_mood_rating_path(@user) %>
<br>

<br>
<table class="ratings-all">
    <tr>
<%= render @mood_ratings %>
</tr>
</table>

consider_water_app/app/views/mood_ratings/new.html.erb
<div class="form">
  <%= render partial: 'form' %>
</div>

consider_water_app/app/views/mood_ratings/show.html.erb
show moods!

consider_water_app/app/views/mood_ratings/update.html.erb
update template!

consider_water_app/app/views/users/new.html.erb
<div class="form">
<h4>Create an account</h4>
  <%= form_for @user do |f| %>
  <%= f.label :username%><br>
  <%= f.text_field :username%><br>
  <%= f.label :password %><br>
  <%= f.password_field :password %><br>
  <%= f.label :password_confirmation %><br>
  <%= f.password_field :password_confirmation %><br>
  <br>
  <%= f.submit "Sign Up", :class => 'signup-button'%><br>
  <% end %>
</div>

consider_water_app/app/views/users/show.html.erb
<div id="user-page"><br>
<h4> Hello, <%= @user.username%>,</h4>
<p> This is your profile page. There isn't a whole lot going on here. </p>

<h6>If you want to delete your account click below. Please note all your journal entries and mood rankings will be permanently destroyed. </h6>

<%=button_to 'DELETE', @user, :method => :delete %>

</div>

consider_water_app/app/views/welcome/index.html.erb
<!-- this div close pushes this element below container div I know I know totally hacky, :-\  -->
<!-- </div> -->
<p class="footer">This website is dedicated to helping people with anxiety pass the time.</p>